### ISSUE TITLE
Validation doesn't work in Windows' tests

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#100]
This is the error trace when trying to validate:

```
2016-05-31 19:07:24 - ERROR - NammuController - Can't connect to ORACC server at http://oracc.museum.upenn.edu.
2016-05-31 19:07:24 - ERROR - NammuController - Error when trying to send first HTTP POST request.
2016-05-31 19:07:24 - ERROR - NammuController - HTTPConnectionPool(host='oracc.museum.upenn.edu', port=8085): Max retries exceeded with url: / (Caused by NewConn
ectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1d>: Failed to establish a new connection: [Errno 20001] getaddrinfo failed',))
Traceback (most recent call last):
  File "__pyclasspath__/nammu/controller/NammuController.py", line 344, in send_command
  File "__pyclasspath__/nammu/controller/NammuController.py", line 422, in send_request
  File "__pyclasspath__/nammu/SOAPClient/SOAPClient$py.class", line 41, in send
  File "C:\Users\raquel\Desktop\nammu-0.0.4-prerelease.jar\Lib\requests\api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\raquel\Desktop\nammu-0.0.4-prerelease.jar\Lib\requests\api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\raquel\Desktop\nammu-0.0.4-prerelease.jar\Lib\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\raquel\Desktop\nammu-0.0.4-prerelease.jar\Lib\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\raquel\Desktop\nammu-0.0.4-prerelease.jar\Lib\requests\adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='oracc.museum.upenn.edu', port=8085): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages
.urllib3.connection.HTTPConnection object at 0x1d>: Failed to establish a new connection: [Errno 20001] getaddrinfo failed',))
```

Two problems:
- [ ] This shouldn't fail like this and raise an exception instead. Code was in place, so needs to be checked.
- [x] The final error message says `Max retries exceeded with url: / `. That `/` doesn't look like the right URL.

**Comment by raquel-ucl** [comment]
Having made no changes and re-testing today, it seems to work fine. Perhaps there was a problem in the server which has now been solved?

The exception is still not being handled correctly, so I'll work on that.
