### ISSUE TITLE
Replace pyyaml with a more recent forked version

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#177]
Maven didn't like PyYaml for some reason, so we can try with this other version and see if it's any better:

http://yaml.readthedocs.io/en/latest/example.html

**Comment by raquel-ucl** [comment]
There is a new version of `pyyaml` that doesn't cause problems, so no need for workarounds.

Note ruamel.yaml didn't work properly: it requires pip installing the `typing` module, but pip fails with a known Jython bug when trying to determine Python's version 

```
  Using cached typing-3.5.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/br/q4r61sf10mgbbdcggxmwb65c0000gn/T/pip-build-z58OSG/typing/setup.py", line 27, in <module>
        package_dir = {2: 'python2', 3: 'src'}[sys.version_info.major]
    AttributeError: 'tuple' object has no attribute 'major'
```
