### ISSUE TITLE
Settings update doesn't merge well

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#185]
In the latest release of Nammu (0.4), there is a new version of settings.yaml (0.2) that includes the key strokes for the split editor. The way the settings are stored in the user's machine is by merging the dictionaries in the installed settings file and the one in the release when their versions differ. Since there are nested dictionaries, I had to do some modifications so that the nested dictionaries also got merged properly. However this doesn't work well yet.

Installing the new version of Nammu in Eleanor's machine has come back with these differences:

```
<   saveFile: VK_S, showHelp: VK_H, splitEditorH: VK_PERIOD, splitEditorV: VK_COMMA,
<   undo: VK_Z, validate: VK_D}
---
>   saveFile: VK_S, showHelp: VK_H, undo: VK_Z, validate: VK_D}
14c13
<   default: [cams/gkab]
---
>   default: [cams/misc]
21c20
< version: 0.2
---
> version: 0.1
```

First and last one are as expected, but the default project has been replaced and it shouldn't.

**Comment by benlaken** [comment]
Started by trying to ensure when yaml is written it comes out with some clean-looking format. This works fine in regular Python 2.7 using [ruamel.yaml](http://yaml.readthedocs.io/en/latest/overview.html) :

```python
path_to_jar = 'settings_files/settings.yaml'
try:
    jar_contents = zipfile.ZipFile(path_to_jar, 'r')
except zipfile.BadZipfile:
    jar_config = ruamel.yaml.load(open(path_to_jar, 'r'), ruamel.yaml.RoundTripLoader)
else:
    jar_config = ruamel.yaml.load(jar_contents.open(yaml_path), ruamel.yaml.RoundTripLoader)

# Erase some fields, and add another
del jar_config['projects']['default']
del jar_config['languages']['Early Akkadian']
jar_config['languages']['BenEase'] = 'ben-x-stuff'

# example printing with structure maintained...
print(ruamel.yaml.dump(jar_config, Dumper=ruamel.yaml.RoundTripDumper))

with open("test.yaml", 'w') as outfile:
    outfile.write(ruamel.yaml.dump(jar_config, Dumper=ruamel.yaml.RoundTripDumper))
```

However, when trying to include this in the Jython version, we run into an error:

```bash
java -jar target/nammu-0.4.jar
Exception in thread "MainThread" Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<string>", line 2, in <module>
  File "__pyclasspath__/nammu/main.py", line 20, in <module>
  File "__pyclasspath__/nammu/controller/NammuController.py", line 28, in <module>
  File "__pyclasspath__/nammu/controller/AtfAreaController.py", line 22, in <module>
  File "__pyclasspath__/nammu/view/AtfAreaView.py", line 29, in <module>
  File "__pyclasspath__/nammu/view/AtfEditArea.py", line 23, in <module>
  File "__pyclasspath__/nammu/utils/__init__.py", line 25, in <module>
  File "/Users/Ben/Work/Python/Programs/nammu/target/nammu-0.4.jar/Lib/ruamel/yaml/__init__.py", line 81, in <module>
  File "/Users/Ben/Work/Python/Programs/nammu/target/nammu-0.4.jar/Lib/ruamel/yaml/main.py", line 6, in <module>
  File "/Users/Ben/Work/Python/Programs/nammu/target/nammu-0.4.jar/Lib/typing$py.class", line 345, in <module>
  File "/Users/Ben/Work/Python/Programs/nammu/target/nammu-0.4.jar/Lib/typing$py.class", line 332, in __new__
  File "/Users/Ben/Work/Python/Programs/nammu/target/nammu-0.4.jar/Lib/typing$py.class", line 100, in assert_no_subclassing
RuntimeError: maximum recursion depth exceeded (Java StackOverflowError)
```

Not sure how to get around this bug, so for now will switch back to working on the main problem, ensuring the merges of the yaml files are correct.

**Comment by benlaken** [comment]
Update the update_yaml_config function in 06e062578a35, and added the skeleton of a test in 06e062578a35bf. To get the test working an issue with maven and PyYaml still needs to be resolved.
