### ISSUE TITLE
Display better error message when Nammu fails to open due to corrupt settings file

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#345]
This comes from reports by @zarpanitu detailed in #339. At the moment we are checking several things around the settings file when Nammu is opened, but we didn't consider the settings file getting emptied or corrupt or being an invalid yaml file. At the very least, we should have a log message in nammu.log that says the file is wrong. Ideally, a pop up window that informs the user about the origin of the problem.

**Comment by giordano** [comment]
I'm looking into this.  For the time being I'm collecting different kind of corruptness of the setting file (`~/.nammu/settings.yaml`).  Maybe we'll end up with a single solution for all cases, but I'm going to report here some of the current problems, as they will probably be useful for testing.

1. Empty setting file, this causes the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python/nammu/controller/NammuController.py", line 68, in __init__
    self.config = get_yaml_config('settings.yaml')
  File "python/nammu/utils/__init__.py", line 143, in get_yaml_config
    update_yaml_config(path_to_jar, yaml_path, path_to_config)
  File "python/nammu/utils/__init__.py", line 252, in update_yaml_config
    (jar_config, local_config,
  File "python/nammu/utils/__init__.py", line 235, in get_config_versions
    local_version = str(local_config['version'])
TypeError: 'NoneType' object is unsubscriptable
```
(see also https://github.com/oracc/nammu/issues/339#issuecomment-415495450).

2. the setting file contains only
```yaml
arabic_area_style
```
which gives this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python/nammu/controller/NammuController.py", line 68, in __init__
    self.config = get_yaml_config('settings.yaml')
  File "python/nammu/utils/__init__.py", line 143, in get_yaml_config
    update_yaml_config(path_to_jar, yaml_path, path_to_config)
  File "python/nammu/utils/__init__.py", line 252, in update_yaml_config
    (jar_config, local_config,
  File "python/nammu/utils/__init__.py", line 235, in get_config_versions
    local_version = str(local_config['version'])
TypeError: str indices must be integers
```

3. the setting file contains only
```yaml
arabic_area_style:
```
which gives this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python/nammu/controller/NammuController.py", line 68, in __init__
    self.config = get_yaml_config('settings.yaml')
  File "python/nammu/utils/__init__.py", line 143, in get_yaml_config
    update_yaml_config(path_to_jar, yaml_path, path_to_config)
  File "python/nammu/utils/__init__.py", line 252, in update_yaml_config
    (jar_config, local_config,
  File "python/nammu/utils/__init__.py", line 235, in get_config_versions
    local_version = str(local_config['version'])
KeyError: 'version'
```
