### ISSUE TITLE
Exception raised when undoing

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#357]
This can be replicated as:

1. Open Nammu from within a jython console.
2. Type a word with more than one letter.
3. Hit the undo button once - it works well.
4. Hit the undo button again - this exception is thrown:

```
Exception in thread "AWT-EventQueue-0" 	at javax.swing.text.GapContent.getChars(GapContent.java:189)
	at javax.swing.text.GapContent.getString(GapContent.java:167)
	at javax.swing.text.AbstractDocument.getText(AbstractDocument.java:770)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)

javax.swing.text.BadLocationException: javax.swing.text.BadLocationException: Invalid location
```

The undo functionality still works, but I'd like to capture this exception or investigate what's throwing it. I'd checked and can't pinpoint where in the code this exception is being raised. IT might have to do with the Edit Area's caret attempting to occupy the position of the character that has just been deleted via undo. 

This is not a problem for users though, since it won't appear in their consoles when they run the jar.

**Comment by raquel-ucl** [comment]
Also it only happens when undoing from the menu button. Seems to be ok when pressing Cmd+Z.

**Comment by raquel-ucl** [comment]
This is also happening after opening new file and after create a new ATF file.

Solution seems to be to be more explicit about emptying the undo manager's discard stack pile, so it doesn't try to undo further than current user task.

**Comment by raquel-ucl** [comment]
Fixed by discarding all events in the edits stack after opening/closing files and creating a new ATF.
