### ISSUE TITLE
File breaks Syntax Highlight

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#87]
When displaying the following file in the text area, there is an error:

`whole_corpus/cams/gkab/00atf/ctn_4_057.atf`

```
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "python/nammu/controller/AtfAreaController.py", line 27, in setAtfAreaText
    self.view.syntax_highlight()
  File "python/nammu/view/AtfAreaView.py", line 164, in syntax_highlight
    mylength = len(splittext[tok.lineno-1])
IndexError: index out of range: 574
```

**Comment by raquel-ucl** [comment]
Not happening anymore. Closing.
